"""feat: creation of sub category model

Revision ID: 0acc26f1a19a
Revises: 0acff660bc25
Create Date: 2023-06-28 11:27:55.206704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0acc26f1a19a'
down_revision = '0acff660bc25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_subcategories',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('sku', sa.String(length=300), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('product_categories_id',
                              sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['product_categories_id'], [
                        'product_categories.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('products', sa.Column(
        'product_subcategories_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'products', 'product_subcategories', [
                          'product_subcategories_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'product_subcategories_id')
    op.drop_table('product_subcategories')
    # ### end Alembic commands ###
